# config/omni_controllers.yaml
wheel1_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel1_joint
  pid: {p: 10.0, i: 0.1, d: 0.0}

wheel2_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel2_joint
  pid: {p: 10.0, i: 0.1, d: 0.0}

wheel3_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel3_joint
  pid: {p: 10.0, i: 0.1, d: 0.0}
