recovery_behaviors:
  - name: clear_costmap        # Tên gọi tùy ý
    type: "clear_costmap_recovery/ClearCostmapRecovery"


  - name: rotate_recovery
    type: "rotate_recovery/RotateRecovery"
    max_rotation_deg: 45            # Mặc định là 45 độ
    rotation_velocity: 0.5          # (rad/s)

